sonar.projectKey=Abhijeet41_JetFoodReceipeMultiModule
sonar.organization=abhijeet41
sonar.host.url=https://sonarcloud.io

sonar.sources=receipe/src/main/java,receipe/src/main/kotlin
sonar.tests=receipe/src/test/java,receipe/src/test/kotlin
sonar.sourceEncoding=UTF-8
sonar.java.binaries=receipe/build/intermediates/javac/debug/classes
sonar.coverage.jacoco.xmlReportPaths=receipe/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
sonar.androidLint.reportPaths=receipe/build/reports/lint-resuts-debug.xml